#version 430 core
layout(local_size_x = 16, local_size_y = 16) in;

// Satellite image input
layout(binding = 0) uniform sampler2D rawTex;
// Building mask image input
layout(binding = 1) uniform sampler2D maskTex;

#define NUM_DIRECTIONS 64

// Buffer that stores shadow scores for 64 directions
layout(std430, binding = 2) buffer AngleScores {
    uint scores[NUM_DIRECTIONS];
};

// For angle ranges (in radians)
uniform float StartAngle;
uniform float EndAngle;

uniform int DistanceThreshold = 25;
uniform float ShadowThreshold;

void main() {
    ivec2 pos = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = textureSize(maskTex, 0);
    if (pos.x >= size.x || pos.y >= size.y) return;

    // Process only pixels that are NOT buildings (according to our building mask)
    float isBuilding = texelFetch(maskTex, pos, 0).r;
    if (isBuilding > 0.5) return;

    // Process only if pixel is dark (likely shadow)
    vec3 rgb = texelFetch(rawTex, pos, 0).rgb;

    // Grayscale for luminance factor
    float luminance = dot(rgb, vec3(0.299, 0.587, 0.114));

    if (luminance >= ShadowThreshold) return;

    // Sample around this piexel in a circle
    float minDistance = float(DistanceThreshold);
    ivec2 closestBuildingPos = ivec2(-1);
    bool foundBuilding = false;

    // Fast search (up to DistanceThreshold)
    for (int dy = -DistanceThreshold; dy <= DistanceThreshold; dy += 2) {
        for (int dx = -DistanceThreshold; dx <= DistanceThreshold; dx += 2) {
            
            // Limit to distanceThreshold circle radius
            if (dx*dx + dy*dy > DistanceThreshold*DistanceThreshold) continue;

            ivec2 checkPos = pos + ivec2(dx, dy);
            if (checkPos.x < 0 || checkPos.x >= size.x || checkPos.y < 0 || checkPos.y >= size.y) continue;

            if (texelFetch(maskTex, checkPos, 0).r > 0.5) {
                // Found a building

                float dist = length(vec2(dx, dy));
                if (dist < minDistance) {
                    minDistance = dist;
                    closestBuildingPos = checkPos;
                    foundBuilding = true;
                }
            }
        }
    }

    // If a dark pixel found their building, it is a candidate for a building's shadow
    if (foundBuilding) {
        // Direction from building to shadow pixel
        vec2 shadowDir = vec2(pos - closestBuildingPos);
        
        float angle = atan(-shadowDir.y, shadowDir.x);
        
        // Map atan func to [0, 2*PI]
        if (angle < 0.0) angle += 6.28318530718;

        // Check angle bounds (StartAngle - EndAngle)

        bool inRange = false;
        if (StartAngle <= EndAngle) {
            inRange = (angle >= StartAngle && angle <= EndAngle);
        } else {
            inRange = (angle >= StartAngle || angle <= EndAngle);
        }

        if (inRange) {
            float angleRange = (EndAngle >= StartAngle) ? (EndAngle - StartAngle) : ((EndAngle + 6.2831853) - StartAngle);
            if (angleRange > 0.00001) {
                float diff = (angle >= StartAngle) ? (angle - StartAngle) : ((angle + 6.2831853) - StartAngle);
                float progress = diff / angleRange;

                // Calculate index
                int target_idx = int(round(progress * float(NUM_DIRECTIONS - 1)));
                target_idx = clamp(target_idx, 0, NUM_DIRECTIONS - 1);

                // Every pixel "votes" once with scaled vote_influence by inverse of max distance radius
                // Shadows closer to a building are more likely to actually be in shadow
                uint voteWeight = uint(clamp(int(float(DistanceThreshold) - minDistance), 1, DistanceThreshold));

                // Add up score for this direction using atomicAdd
                atomicAdd(scores[target_idx], voteWeight);
            }
        }
    }
}
