#version 430 core
layout(local_size_x = 16, local_size_y = 16) in;

layout(binding = 0, rgba8) uniform readonly image2D rawTex;
layout(binding = 1, rgba8) uniform readonly image2D maskTex;

layout(binding = 2, r8) writeonly uniform image2D shadowMaskTex;
layout(binding = 3, r8) writeonly uniform image2D heightMapTex;

uniform float ShadowAngle;    
uniform int DistanceThreshold = 30;
uniform float ShadowThreshold = 0.35; 

void main() {
    ivec2 pos = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(maskTex);
    if (pos.x >= size.x || pos.y >= size.y) return;

    float isBuilding = imageLoad(maskTex, pos).r;

    if (isBuilding > 0.5) {
        imageStore(shadowMaskTex, pos, vec4(0.0));
        imageStore(heightMapTex, pos, vec4(1.0));
        return;
    }

    vec2 sunDir = -vec2(cos(ShadowAngle), -sin(ShadowAngle));

    // DDA algorithm
    vec2 absDir = abs(sunDir);
    vec2 rayStep = vec2(0.0);
    if (absDir.x > absDir.y) {
        rayStep = vec2(sign(sunDir.x), sunDir.y / absDir.x);
    } else {
        rayStep = vec2(sunDir.x / absDir.y, sign(sunDir.y));
    }

    bool hitBuilding = false;
    int stepsToBuilding = 0;
    vec2 currentRayPos = vec2(pos);

    // Raytrace back to the sun
    for (int step = 1; step <= DistanceThreshold; step++) {
        currentRayPos += rayStep;
        ivec2 samplePos = ivec2(round(currentRayPos));

        if (samplePos.x < 0 || samplePos.x >= size.x || samplePos.y < 0 || samplePos.y >= size.y) break;

        // If we hit a building, it obstructs the light
        if (imageLoad(maskTex, samplePos).r > 0.5) {
            hitBuilding = true;
            stepsToBuilding = step;
            break; // FOund obstacle building
        }
    }

    // Take luminace relative to ground tint
    vec3 rgb = imageLoad(rawTex, pos).rgb;
    float luminance = dot(rgb, vec3(0.3, 0.6, 0.1));

    // IF blocked by building AND satellite has dark pixel
    if (hitBuilding && luminance < ShadowThreshold) {
        imageStore(shadowMaskTex, pos, vec4(1.0)); // Mark as SHADOW
        
        // Save distance to building to put in a heightmap (later use)
        float normHeight = float(DistanceThreshold - stepsToBuilding) / float(DistanceThreshold);
        imageStore(heightMapTex, pos, vec4(normHeight));
    } else {
        // Pixel is lit by the sun
        imageStore(shadowMaskTex, pos, vec4(0.0));
        imageStore(heightMapTex, pos, vec4(0.0));
    }
}
